//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentInformationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CombatVehicles
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string SerialNo { get; set; }
        public Nullable<long> Equipment { get; set; }
        public Nullable<long> Image { get; set; }
        public string Model { get; set; }
        public string VehiclesNo { get; set; }
        public string MotorModel { get; set; }
        public string MotorNo { get; set; }
        public string Factory { get; set; }
        public string ProductionDate { get; set; }
        public string OemNo { get; set; }
        public string Mass { get; set; }
        public string Tankage { get; set; }
        public string OverallSize { get; set; }
        public string ExpandedSize { get; set; }
        public string WheelBase { get; set; }
        public string FuelType { get; set; }
        public string DrivingModel { get; set; }
        public string Mileage { get; set; }
        public string Output { get; set; }
        public string LicenseCarry { get; set; }
        public string SubDepartment { get; set; }
        public string VehicleChargers { get; set; }
        public string UseType { get; set; }
        public string VehicleSpotNo { get; set; }
        public string FaultDescri { get; set; }
    
        public virtual CombatEquipment CombatEquipment { get; set; }
        public virtual VehiclesImage VehiclesImage { get; set; }
    }
}
