//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentInformationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CombatVehicles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CombatVehicles()
        {
            this.OilEngine = new HashSet<OilEngine>();
        }
    
        public string SerialNo { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public string VehiclesNo { get; set; }
        public string MotorModel { get; set; }
        public string TechCondition { get; set; }
        public string Factory { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public string Mass { get; set; }
        public string Tankage { get; set; }
        public string OverallSize { get; set; }
        public string FuelType { get; set; }
        public string DrivingModel { get; set; }
        public string Mileage { get; set; }
        public string Output { get; set; }
        public string LicenseCarry { get; set; }
        public string VehicleChargers { get; set; }
        public string VehicleSpotNo { get; set; }
        public string VehicleDescri { get; set; }
        public bool CombineOe { get; set; }
        public string Equipment { get; set; }
    
        public virtual CombatEquipment CombatEquipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OilEngine> OilEngine { get; set; }
    }
}
