//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentInformationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CombatVehicles
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string SerialNo { get; set; }
        public Nullable<long> Equipment { get; set; }
        public Nullable<long> Image { get; set; }
    
        public virtual CombatEquipment CombatEquipment { get; set; }
        public virtual VehiclesImage VehiclesImage { get; set; }
    }
}
