//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.DataProvider;
using LinqToDB.Mapping;

namespace EquipmentInformationData
{
	/// <summary>
	/// Database       : EquipmentImages
	/// Data Source    : EquipmentImages
	/// Server Version : 3.9.2
	/// </summary>
	public partial class EquipmentImagesDB : LinqToDB.Data.DataConnection
	{
		public ITable<EquipmentImage> EquipmentImages { get { return this.GetTable<EquipmentImage>(); } }

		public EquipmentImagesDB()
		{
			InitDataContext();
		}

		public EquipmentImagesDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}
		public EquipmentImagesDB(IDataProvider dataProvider, string configuration)
			: base(dataProvider, configuration)
		{
			InitDataContext();
		}


		partial void InitDataContext();
	}

	[Table("EquipmentImage")]
	public partial class EquipmentImage
	{
		[PrimaryKey, Identity] public long   ID       { get; set; } // integer
		[Column,     Nullable] public string Name     { get; set; } // nvarchar(254)
		[Column,     Nullable] public byte[] Images   { get; set; } // image
		[Column,     Nullable] public string SerialNo { get; set; } // nvarchar(254)
	}

	public static partial class TableExtensions
	{
		public static EquipmentImage Find(this ITable<EquipmentImage> table, long ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}
	}
}
