//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace EquipmentInformationData
{
	/// <summary>
	/// Database       : EquipmentManagement
	/// Data Source    : EquipmentManagement
	/// Server Version : 3.9.2
	/// </summary>
	public partial class EquipmentManagementDB : LinqToDB.Data.DataConnection
	{
		public ITable<CombatEquipment> CombatEquipments { get { return this.GetTable<CombatEquipment>(); } }
		public ITable<CombatVehicle>   CombatVehicles   { get { return this.GetTable<CombatVehicle>(); } }
		public ITable<Event>           Events           { get { return this.GetTable<Event>(); } }
		public ITable<EventData>       EventData        { get { return this.GetTable<EventData>(); } }
		public ITable<Material>        Materials        { get { return this.GetTable<Material>(); } }
		public ITable<OilEngine>       OilEngines       { get { return this.GetTable<OilEngine>(); } }

		public EquipmentManagementDB()
		{
			InitDataContext();
		}

		public EquipmentManagementDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("CombatEquipment")]
	public partial class CombatEquipment
	{
		[PrimaryKey, NotNull    ] public string   SerialNo       { get; set; } // nvarchar(16)
		[Column,     NotNull    ] public string   Name           { get; set; } // nvarchar(20)
		[Column,        Nullable] public string   MajorCategory  { get; set; } // nvarchar(10)
		[Column,        Nullable] public string   Model          { get; set; } // nvarchar(10)
		[Column,        Nullable] public string   SubDepartment  { get; set; } // nvarchar(5)
		[Column,        Nullable] public string   TechCondition  { get; set; } // nvarchar(6)
		[Column,        Nullable] public string   UseCondition   { get; set; } // nvarchar(6)
		[Column,        Nullable] public string   Factory        { get; set; } // nvarchar(20)
		[Column,        Nullable] public string   OemNo          { get; set; } // nvarchar(10)
		[Column,     NotNull    ] public DateTime ProductionDate { get; set; } // date
		[Column,        Nullable] public string   InventorySpot  { get; set; } // text(max)
		[Column,        Nullable] public string   MajorComp      { get; set; } // text(max)
		[Column,        Nullable] public string   MainUsage      { get; set; } // text(max)
		[Column,        Nullable] public string   PerformIndex   { get; set; } // text(max)
		[Column,        Nullable] public string   UseMethod      { get; set; } // text(max)
		[Column,        Nullable] public string   Manager        { get; set; } // nvarchar(4)
		[Column,        Nullable] public string   Technician     { get; set; } // nvarchar(4)
		[Column,        Nullable] public string   TechRemould    { get; set; } // text(max)
		[Column,        Nullable] public string   SetupVideo     { get; set; } // text(max)

		#region Associations

		/// <summary>
		/// FK_Events_0_0_BackReference
		/// </summary>
		[Association(ThisKey="SerialNo", OtherKey="Equipment", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<Event> Events00 { get; set; }

		/// <summary>
		/// FK_Material_0_0_BackReference
		/// </summary>
		[Association(ThisKey="SerialNo", OtherKey="Equipment", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<Material> Material00 { get; set; }

		/// <summary>
		/// FK_CombatVehicles_0_0_BackReference
		/// </summary>
		[Association(ThisKey="SerialNo", OtherKey="Equipment", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<CombatVehicle> CombatVehicles00 { get; set; }

		#endregion
	}

	[Table("CombatVehicles")]
	public partial class CombatVehicle
	{
		[PrimaryKey, NotNull    ] public string   SerialNo        { get; set; } // nvarchar(16)
		[Column,     NotNull    ] public string   Name            { get; set; } // nvarchar(20)
		[Column,        Nullable] public string   Model           { get; set; } // nvarchar(10)
		[Column,        Nullable] public string   VehiclesNo      { get; set; } // nvarchar(7)
		[Column,        Nullable] public string   MotorModel      { get; set; } // nvarchar(10)
		[Column,        Nullable] public string   TechCondition   { get; set; } // nvarchar(4)
		[Column,        Nullable] public string   Factory         { get; set; } // nvarchar(10)
		[Column,     NotNull    ] public DateTime ProductionDate  { get; set; } // date
		[Column,        Nullable] public string   Mass            { get; set; } // nvarchar(5)
		[Column,        Nullable] public string   Tankage         { get; set; } // nvarchar(3)
		[Column,        Nullable] public string   OverallSize     { get; set; } // nvarchar(16)
		[Column,        Nullable] public string   FuelType        { get; set; } // nvarchar(2)
		[Column,        Nullable] public string   DrivingModel    { get; set; } // nvarchar(6)
		[Column,        Nullable] public string   Mileage         { get; set; } // nvarchar(6)
		[Column,        Nullable] public string   Output          { get; set; } // nvarchar(3)
		[Column,        Nullable] public string   LicenseCarry    { get; set; } // nvarchar(2)
		[Column,        Nullable] public string   VehicleChargers { get; set; } // nvarchar(4)
		[Column,        Nullable] public string   VehicleSpotNo   { get; set; } // nvarchar(3)
		[Column,        Nullable] public string   VehicleDescri   { get; set; } // text(max)
		[Column,     NotNull    ] public bool     CombineOe       { get; set; } // bool
		[Column,        Nullable] public string   Equipment       { get; set; } // nvarchar(16)

		#region Associations

		/// <summary>
		/// FK_CombatVehicles_0_0
		/// </summary>
		[Association(ThisKey="Equipment", OtherKey="SerialNo", CanBeNull=true, KeyName="FK_CombatVehicles_0_0", BackReferenceName="CombatVehicles00")]
		public CombatEquipment FK_00 { get; set; }

		/// <summary>
		/// FK_OilEngine_0_0_BackReference
		/// </summary>
		[Association(ThisKey="SerialNo", OtherKey="Vehicle", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<OilEngine> OilEngine00 { get; set; }

		#endregion
	}

	[Table("Events")]
	public partial class Event
	{
		[PrimaryKey, NotNull    ] public string   No            { get; set; } // nvarchar(16)
		[Column,        Nullable] public string   Name          { get; set; } // nvarchar(10)
		[Column,     NotNull    ] public DateTime StartTime     { get; set; } // date
		[Column,     NotNull    ] public DateTime EndTime       { get; set; } // date
		[Column,        Nullable] public string   Address       { get; set; } // nvarchar(5)
		[Column,        Nullable] public string   EventType     { get; set; } // nvarchar(4)
		[Column,        Nullable] public string   SpecificType  { get; set; } // nvarchar(4)
		[Column,        Nullable] public string   Code          { get; set; } // nvarchar(5)
		[Column,        Nullable] public string   NoInEvents    { get; set; } // nvarchar(4)
		[Column,        Nullable] public string   HigherUnit    { get; set; } // nvarchar(10)
		[Column,        Nullable] public string   Executor      { get; set; } // nvarchar(4)
		[Column,        Nullable] public string   PublishUnit   { get; set; } // nvarchar(5)
		[Column,     NotNull    ] public DateTime PublishDate   { get; set; } // date
		[Column,        Nullable] public string   Publisher     { get; set; } // nvarchar(4)
		[Column,        Nullable] public string   According     { get; set; } // text(max)
		[Column,        Nullable] public string   PeopleDescri  { get; set; } // nvarchar(50)
		[Column,        Nullable] public string   ProcessDescri { get; set; } // text(max)
		[Column,        Nullable] public string   HandleStep    { get; set; } // text(max)
		[Column,        Nullable] public string   Problem       { get; set; } // text(max)
		[Column,        Nullable] public string   Remarks       { get; set; } // text(max)
		[Column,        Nullable] public string   Equipment     { get; set; } // nvarchar(16)

		#region Associations

		/// <summary>
		/// FK_Events_0_0
		/// </summary>
		[Association(ThisKey="Equipment", OtherKey="SerialNo", CanBeNull=true, KeyName="FK_Events_0_0", BackReferenceName="Events00")]
		public CombatEquipment FK_00 { get; set; }

		/// <summary>
		/// FK_EventData_0_0_BackReference
		/// </summary>
		[Association(ThisKey="No", OtherKey="EventsNo", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<EventData> EventData00 { get; set; }

		#endregion
	}

	[Table("EventData")]
	public partial class EventData
	{
		[PrimaryKey, Identity] public long   ID       { get; set; } // integer
		[Column,     Nullable] public string Name     { get; set; } // nvarchar(100)
		[Column,     Nullable] public string Spot     { get; set; } // nvarchar(10)
		[Column,     Nullable] public string EventsNo { get; set; } // nvarchar(16)

		#region Associations

		/// <summary>
		/// FK_EventData_0_0
		/// </summary>
		[Association(ThisKey="EventsNo", OtherKey="No", CanBeNull=true, KeyName="FK_EventData_0_0", BackReferenceName="EventData00")]
		public Event FK_00 { get; set; }

		#endregion
	}

	[Table("Material")]
	public partial class Material
	{
		[PrimaryKey, NotNull    ] public string   No           { get; set; } // nvarchar(16)
		[Column,        Nullable] public string   Name         { get; set; } // nvarchar(20)
		[Column,        Nullable] public string   Type         { get; set; } // nvarchar(6)
		[Column,        Nullable] public string   PaperSize    { get; set; } // nvarchar(4)
		[Column,        Nullable] public string   Pagination   { get; set; } // nvarchar(3)
		[Column,        Nullable] public string   Edition      { get; set; } // nvarchar(3)
		[Column,        Nullable] public string   Volume       { get; set; } // nvarchar(2)
		[Column,     NotNull    ] public DateTime Date         { get; set; } // date
		[Column,        Nullable] public string   DocumentLink { get; set; } // text(max)
		[Column,        Nullable] public string   StoreSpot    { get; set; } // nvarchar(5)
		[Column,        Nullable] public string   Content      { get; set; } // text(max)
		[Column,        Nullable] public string   Equipment    { get; set; } // nvarchar(16)

		#region Associations

		/// <summary>
		/// FK_Material_0_0
		/// </summary>
		[Association(ThisKey="Equipment", OtherKey="SerialNo", CanBeNull=true, KeyName="FK_Material_0_0", BackReferenceName="Material00")]
		public CombatEquipment FK_00 { get; set; }

		#endregion
	}

	[Table("OilEngine")]
	public partial class OilEngine
	{
		[PrimaryKey, NotNull    ] public string   OeNo          { get; set; } // nvarchar(16)
		[Column,        Nullable] public string   OeModel       { get; set; } // nvarchar(10)
		[Column,        Nullable] public string   OutPower      { get; set; } // nvarchar(3)
		[Column,        Nullable] public string   TechCondition { get; set; } // nvarchar(6)
		[Column,        Nullable] public string   WorkHour      { get; set; } // nvarchar(4)
		[Column,        Nullable] public string   OeFactory     { get; set; } // nvarchar(10)
		[Column,     NotNull    ] public DateTime OeDate        { get; set; } // date
		[Column,        Nullable] public string   OeOemNo       { get; set; } // nvarchar(10)
		[Column,     NotNull    ] public string   MotorModel    { get; set; } // nvarchar(10)
		[Column,        Nullable] public string   MotorPower    { get; set; } // nvarchar(3)
		[Column,        Nullable] public string   MotorFuel     { get; set; } // nvarchar(2)
		[Column,        Nullable] public string   MotorTankage  { get; set; } // nvarchar(3)
		[Column,        Nullable] public string   MotorFactory  { get; set; } // nvarchar(10)
		[Column,     NotNull    ] public DateTime MotorDate     { get; set; } // date
		[Column,        Nullable] public string   MotorOemNo    { get; set; } // nvarchar(10)
		[Column,        Nullable] public string   FaultDescri   { get; set; } // text(max)
		[Column,        Nullable] public string   Vehicle       { get; set; } // nvarchar(16)

		#region Associations

		/// <summary>
		/// FK_OilEngine_0_0
		/// </summary>
		[Association(ThisKey="Vehicle", OtherKey="SerialNo", CanBeNull=true, KeyName="FK_OilEngine_0_0", BackReferenceName="OilEngine00")]
		public CombatVehicle FK_00 { get; set; }

		#endregion
	}

	public static partial class TableExtensions
	{
		public static CombatEquipment Find(this ITable<CombatEquipment> table, string SerialNo)
		{
			return table.FirstOrDefault(t =>
				t.SerialNo == SerialNo);
		}

		public static CombatVehicle Find(this ITable<CombatVehicle> table, string SerialNo)
		{
			return table.FirstOrDefault(t =>
				t.SerialNo == SerialNo);
		}

		public static Event Find(this ITable<Event> table, string No)
		{
			return table.FirstOrDefault(t =>
				t.No == No);
		}

		public static EventData Find(this ITable<EventData> table, long ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static Material Find(this ITable<Material> table, string No)
		{
			return table.FirstOrDefault(t =>
				t.No == No);
		}

		public static OilEngine Find(this ITable<OilEngine> table, string OeNo)
		{
			return table.FirstOrDefault(t =>
				t.OeNo == OeNo);
		}
	}
}
