//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.DataProvider;
using LinqToDB.Mapping;

namespace EquipmentInformationData
{
	/// <summary>
	/// Database       : EventsImages
	/// Data Source    : EventsImages
	/// Server Version : 3.9.2
	/// </summary>
	public partial class EventsImagesDB : LinqToDB.Data.DataConnection
	{
		public ITable<EventsImage> EventsImages { get { return this.GetTable<EventsImage>(); } }

		public EventsImagesDB()
		{
			InitDataContext();
		}

		public EventsImagesDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		public EventsImagesDB(IDataProvider dataProvider, string configuration)
			: base(dataProvider, configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("EventsImage")]
	public partial class EventsImage
	{
		[PrimaryKey, Identity] public long   ID       { get; set; } // integer
		[Column,     Nullable] public string Name     { get; set; } // nvarchar(254)
		[Column,     Nullable] public byte[] Images   { get; set; } // image
		[Column,     Nullable] public string SerialNo { get; set; } // nvarchar(254)
	}

	public static partial class TableExtensions
	{
		public static EventsImage Find(this ITable<EventsImage> table, long ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}
	}
}
