//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.DataProvider;
using LinqToDB.Mapping;

namespace EquipmentInformationData
{
	/// <summary>
	/// Database       : OilEngineImages
	/// Data Source    : OilEngineImages
	/// Server Version : 3.9.2
	/// </summary>
	public partial class OilEngineImagesDB : LinqToDB.Data.DataConnection
	{
		public ITable<OilEngineImage> OilEngineImages { get { return this.GetTable<OilEngineImage>(); } }

		public OilEngineImagesDB()
		{
			InitDataContext();
		}

		public OilEngineImagesDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		public OilEngineImagesDB(IDataProvider dataProvider, string configuration)
			: base(dataProvider, configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("OilEngineImage")]
	public partial class OilEngineImage
	{
		[PrimaryKey, Identity] public long   ID       { get; set; } // integer
		[Column,     Nullable] public string Name     { get; set; } // nvarchar(254)
		[Column,     Nullable] public byte[] Images   { get; set; } // image
		[Column,     Nullable] public string SerialNo { get; set; } // nvarchar(254)
	}

	public static partial class TableExtensions
	{
		public static OilEngineImage Find(this ITable<OilEngineImage> table, long ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}
	}
}
