//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentInformationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OilEngine
    {
        public string OeNo { get; set; }
        public string OeModel { get; set; }
        public string OutPower { get; set; }
        public string TechCondition { get; set; }
        public string WorkHour { get; set; }
        public string OeFactory { get; set; }
        public System.DateTime OeDate { get; set; }
        public string OeOemNo { get; set; }
        public string MotorModel { get; set; }
        public string MotorPower { get; set; }
        public string MotorFuel { get; set; }
        public string MotorTankage { get; set; }
        public string MotorFactory { get; set; }
        public System.DateTime MotorDate { get; set; }
        public string MotorOemNo { get; set; }
        public string FaultDescri { get; set; }
        public string Vehicle { get; set; }
    
        public virtual CombatVehicles CombatVehicles { get; set; }
    }
}
