//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentInformationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpareParts
    {
        public string SerialNo { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public string Factory { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public string StoreSpot { get; set; }
        public System.DateTime StoreDate { get; set; }
        public string Amount { get; set; }
        public string UseType { get; set; }
        public string Status { get; set; }
    }
}
