//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.DataProvider;
using LinqToDB.Mapping;

namespace EquipmentInformationData
{
	/// <summary>
	/// Database       : SparePartManagement
	/// Data Source    : SparePartManagement
	/// Server Version : 3.9.2
	/// </summary>
	public partial class SparePartManagementDB : LinqToDB.Data.DataConnection
	{
		public ITable<SparePart> SpareParts { get { return this.GetTable<SparePart>(); } }

		public SparePartManagementDB()
		{
			InitDataContext();
		}

		public SparePartManagementDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		public SparePartManagementDB(IDataProvider dataProvider, string configuration)
			: base(dataProvider, configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("SpareParts")]
	public partial class SparePart
	{
		[PrimaryKey, NotNull    ] public string   SerialNo       { get; set; } // nvarchar(254)
		[Column,        Nullable] public string   Name           { get; set; } // nvarchar(254)
		[Column,        Nullable] public string   Model          { get; set; } // nvarchar(254)
		[Column,        Nullable] public string   Factory        { get; set; } // nvarchar(254)
		[Column,     NotNull    ] public DateTime ProductionDate { get; set; } // date
		[Column,        Nullable] public string   StoreSpot      { get; set; } // nvarchar(254)
		[Column,     NotNull    ] public DateTime StoreDate      { get; set; } // date
		[Column,        Nullable] public string   Amount         { get; set; } // nvarchar(254)
		[Column,        Nullable] public string   UseType        { get; set; } // nvarchar(254)
		[Column,        Nullable] public string   Status         { get; set; } // nvarchar(254)
	}

	public static partial class TableExtensions
	{
		public static SparePart Find(this ITable<SparePart> table, string SerialNo)
		{
			return table.FirstOrDefault(t =>
				t.SerialNo == SerialNo);
		}
	}
}
