//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.DataProvider;
using LinqToDB.Mapping;

namespace EquipmentInformationData
{
    /// <summary>
    /// Database       : VehiclesImages
    /// Data Source    : VehiclesImages
    /// Server Version : 3.9.2
    /// </summary>
    public partial class VehiclesImagesDB : LinqToDB.Data.DataConnection
    {
        public ITable<VehiclesImage> VehiclesImages { get { return this.GetTable<VehiclesImage>(); } }

        public VehiclesImagesDB()
        {
            InitDataContext();
        }

        public VehiclesImagesDB(string configuration)
            : base(configuration)
        {
            InitDataContext();
        }

        public VehiclesImagesDB(IDataProvider dataProvider, string configuration)
            : base(dataProvider, configuration)
        {
            InitDataContext();
        }

        partial void InitDataContext();
    }

    [Table("VehiclesImage")]
    public partial class VehiclesImage
    {
        [PrimaryKey, Identity]
        public long ID { get; set; } // integer
        [Column, Nullable]
        public string Name { get; set; } // nvarchar(254)
        [Column, Nullable]
        public byte[] Images { get; set; } // image
        [Column, Nullable]
        public string SerialNo { get; set; } // nvarchar(254)
    }

    public static partial class TableExtensions
    {
        public static VehiclesImage Find(this ITable<VehiclesImage> table, long ID)
        {
            return table.FirstOrDefault(t =>
                t.ID == ID);
        }
    }
}
